name: API CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
    - run: echo "ENV VERSION=$GITHUB_SHA" >> ./Dockerfile
    - name: Build the Docker image
      run: docker build ./api --file ./api/Dockerfile --tag ghcr.io/gessfred/example-api:$GITHUB_SHA
    - run: docker push ghcr.io/gessfred/example-api:$GITHUB_SHA
    - run: docker build ./api --file ./api/Dockerfile --tag ghcr.io/gessfred/example-api:latest
    - run: docker push ghcr.io/gessfred/example-api:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Test API
      run: |
        cd api
        pip install -r requirements.txt
        pytest
      

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Install doctl
      uses: digitalocean/action-doctl@v2.3.0
      with:
        token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        version: 1.91.0
    # - run: sudo snap install doctl
    # - run: sudo snap connect doctl:kube-config
    # - run: sudo ls /home/runner/
    # - run: sudo mkdir /home/runner/.config/doctl
    # - run: sudo doctl auth init -t ${{ secrets.DIGITAL_OCEAN_TOKEN }}
    # - run: sudo apt-get install -y ca-certificates curl
    # - run: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    # - run: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    # - run: sudo apt-get update -y && sudo apt-get install -y kubectl
    - run: /opt/hostedtoolcache/doctl/1.91.0/x64/doctl version
    - run: sudo ls /home/runner/.config/doctl/
    - run: sudo mkdir /root/.kube
    - run: sudo /opt/hostedtoolcache/doctl/1.91.0/x64/doctl kubernetes cluster kubeconfig save k8s-amiscan-1-22-7-do-0-fra1-1648193990670
    - run: sed -i "s/:latest/:${GITHUB_SHA}/g" ./api/deployment.yaml
    - run: sudo kubectl config get-contexts
    - run: sudo kubectl config use-context do-fra1-k8s-amiscan-1-22-7-do-0-fra1-1648193990670
    - run: sudo kubectl apply -f ./api/deployment.yaml
      name: Shipping... 